engines:
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - "app/**/*"
  - "*.coffee"
  - "*.js"
exclude_paths:
- app/templates/**/*
- test/**/*
- slide/**/*
